name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

permissions: write-all

jobs:
  Release:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}
    env:
      XVFB_PFX: ${{ (matrix.os == 'ubuntu-latest' && 'xvfb-run --auto-servernum -- ') || '' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install build essentials (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install rpm

      - name: Install build essentials (macOS & Linux)
        if: matrix.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          npm install -g node-gyp

      - name: Install deps
        if: matrix.os != 'windows-latest'
        run: ${{ env.XVFB_PFX }}yarn

      - name: Rebuild native dependencies for current architecture
        run: |
          ${{ env.XVFB_PFX }}npm rebuild --target_arch=${{ matrix.arch }}
          ${{ env.XVFB_PFX }}./node_modules/.bin/electron-rebuild --arch=${{ matrix.arch }}

      - name: Build/release Electron app
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          ARCH: ${{ matrix.arch }}
        run: yarn build --${{ matrix.arch }} || yarn build --${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: VutronMusic-win-installer-${{ matrix.arch }}
          path: release/*/VutronMusic*_${{ matrix.arch }}.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: VutronMusic-win-portable-${{ matrix.arch }}
          path: release/*/VutronMusic*_${{ matrix.arch }} Portable.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'macos-latest'
        with:
          name: VutronMusic-mac-${{ matrix.arch }}
          path: release/*/VutronMusic*_${{ matrix.arch }}.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: VutronMusic-linux-snap-${{ matrix.arch }}
          path: release/*/VutronMusic*.snap
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: VutronMusic-linux-AppImage-${{ matrix.arch }}
          path: release/*/VutronMusic*.AppImage
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: VutronMusic-linux-deb-${{ matrix.arch }}
          path: release/*/VutronMusic*.deb
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: VutronMusic-linux-rpm-${{ matrix.arch }}
          path: release/*/VutronMusic*.rpm
          if-no-files-found: ignore
